name: GitHub Actions Deploy Frontend To Vercel Prod
env:
  VERCEL_ORG_ID: team_yvQ4u76TKmU15P6zyHzRNwZk
  VERCEL_PROJECT_ID: prj_dx5sjer4WcV7Ju3GX1dJZ3PyF0v5

on:
  push:
    branches: ["release"]

jobs:
  test:
    uses: ENSE7011/Assignment-1/.github/workflows/lint-build-test.yml@release

  deploy-prod-backend:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install vercel cli node.js
        run: npm install --global vercel@canary
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=nhfeo0HOUa6eEw5SGQsvpXHe
      - name: Build Project Artifacts
        run: vercel build --prod --token=nhfeo0HOUa6eEw5SGQsvpXHe
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=nhfeo0HOUa6eEw5SGQsvpXHe
