name: GitHub Actions Deploy Backend To Vercel Prod
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches: ['release']

jobs:
  test:
    uses: ENSE7011/Assignment-1/.github/workflows/lint-build-test.yml@main

  deploy-prod-backend:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install vercel cli node.js
        run: npm install --global vercel@canary
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=$nhfeo0HOUa6eEw5SGQsvpXHe
      - name: Build Project Artifacts
        run: vercel build --prod --token=$nhfeo0HOUa6eEw5SGQsvpXHe
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=$nhfeo0HOUa6eEw5SGQsvpXHe
