name: GitHub Actions Deploy Backend To Vercel Preview
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches: ['main']

jobs:
  deploy-preview-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install vercel cli node.js
        run: npm install --global vercel@canary
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=nhfeo0HOUa6eEw5SGQsvpXHe
      - name: Build Project Artifacts
        run: vercel build --preview --token=nhfeo0HOUa6eEw5SGQsvpXHe
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --preview --token=nhfeo0HOUa6eEw5SGQsvpXHe
