name: GitHub Actions Deploy Production

on:
  push:
    branches: ["release"]

jobs:
  test:
    uses: ENSE7011/Assignment-1/.github/workflows/lint-build-test.yml@release

  deploy-prod-backend:
    needs: test
    uses: ENSE7011/Assignment-1/.github/workflows/deploy-backend-vercel-prod.yml@release

  deploy-prod-frontend:
    needs: [test, deploy-prod-backend]
    uses: ENSE7011/Assignment-1/.github/workflows/deploy-frontend-vercel-prod.yml@release
